version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./code:/app/code


  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ocn217
      MYSQL_DATABASE: account
      MYSQL_HOST: localhost
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./seed:/docker-entrypoint-initdb.d


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_HOST: db
        PMA_USER: root
        PMA_PASSWORD: ocn217
      ports:
        - "82:80"




   # redis:
   #   image: redis:latest
   #   container_name: redis
   #   restart: always
   #   ports:
   #     - "6379:6379"
   #   volumes:
   #     - ./data/redis:/data

