version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile   
    ports:
      - "80:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: hej
      MYSQL_DATABASE: booli
    volumes:
      - ./code:/app/code


  db:
    image: mysql
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: hej
      MYSQL_DATABASE: booli
    command: --default-authentication-plugin=mysql_native_password
    volumes:
       - ./seed:/docker-entrypoint-initdb.d


  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        MYSQL_HOST: db
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: hej
        MYSQL_DATABASE: booli
      ports:
        - "82:80"


   # redis:
   #   image: redis:latest
   #   container_name: redis
   #   restart: always
   #   ports:
   #     - "6379:6379"
   #   volumes:
   #     - ./data/redis:/data